export const prioritizedCountries = [
    // Prioritized European countries
    "Sweden",
    "Germany",

    // Other European countries
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",

    // Prioritized non-European countries
    "Australia",
    "Canada",
    "United States",
    "United Kingdom",

    // Other countries (alphabetical order)
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia", // Already listed above but included here for completeness
    "Austria", // Already listed above but included here for completeness
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium", // Already listed above but included here for completeness
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria", // Already listed above but included here for completeness
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada", // Already listed above but included here for completeness
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia", // Already listed above but included here for completeness
    "Cuba",
    "Cyprus", // Already listed above but included here for completeness
    "Czech Republic", // Already listed above but included here for completeness
    "Democratic Republic of the Congo",
    "Denmark", // Already listed above but included here for completeness
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Estonia", // Already listed above but included here for completeness
    "Ethiopia",
    "Fiji",
    "Finland", // Already listed above but included here for completeness
    "France", // Already listed above but included here for completeness
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany", // Already listed above but included here for completeness
    "Ghana",
    "Greece", // Already listed above but included here for completeness
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary", // Already listed above but included here for completeness
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland", // Already listed above but included here for completeness
    "Israel",
    "Italy", // Already listed above but included here for completeness
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia", // Already listed above but included here for completeness
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania", // Already listed above but included here for completeness
    "Luxembourg", // Already listed above but included here for completeness
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta", // Already listed above but included here for completeness
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands", // Already listed above but included here for completeness
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland", // Already listed above but included here for completeness
    "Portugal", // Already listed above but included here for completeness
    "Qatar",
    "Republic of the Congo",
    "Romania", // Already listed above but included here for completeness
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé and Príncipe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia", // Already listed above but included here for completeness
    "Slovenia", // Already listed above but included here for completeness
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain", // Already listed above but included here for completeness
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden", // Already listed above but included here for completeness
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom", // Already listed above but included here for completeness
    "United States", // Already listed above but included here for completeness
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];